services:
  db-traker-bot:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: db-traker-bot
    ports:
      - "${SQLSERVER_PORT:-1433}:1433"
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "${SA_PASSWORD}"
      TZ: America/Sao_Paulo
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - TraketBot_Network
    restart: always

  trakerbot-api:
    container_name: TrakerBot-API
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - db-traker-bot
    environment:
      TZ: America/Sao_Paulo
    ports:
      - "8081:8080"
    # volumes:
    #   - .:/app
    networks:
      - TraketBot_Network

volumes:
  sqlserver_data:
    driver: local

networks:
  TraketBot_Network:
    driver: bridge
